version: '3'

volumes:
  app_data:
  mysql_data:
    
services:
  db: 
    image: mysql:5.7
    restart: always
    env_file:
      - .dev.env
    ports:
      - "3308:3306"
    volumes:  
      - ./mysql_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec puma -C config/puma.rb  
    env_file:
      - .dev.env
    volumes:
      - .:/rails-boot-starter
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db 
