version: '3'
volumes:  
  mysql_data: {} 
services:  
  app:    
    build:      
      context: .      
      dockerfile: ./docker/Dockerfile.prod
    env_file:
      - .prod.env    
    depends_on:      
      - db  
  db:    
    image: mysql:5.7
    restart: always
    env_file:
      - .prod.env
    volumes:
      - mysql_data:/var/lib/mysql  
    ports:
      - 3306:3306 
  web:    
    build:      
      context: .      
      dockerfile: ./docker/Dockerfile.nginx    
    depends_on:      
      - app    
    ports:      
      - 80:80
      