version: '3'

volumes:
  app-data:
  mysql-data:
    
services:
  db: 
    image: mysql:5.7
    restart: always
    env_file:
      - .dev.env
    ports:
      - "3308:3306"
    volumes:  
      - ./mysql-data:/var/lib/mysql
  app:
    build: .
    env_file:
      - .dev.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/var/www/rails-boot-starter
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db 
