:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:timeout: 30
# :queues:
#   - [low_priority, 1]
#   - [high_priority, 2] # high priority

:schedule:
  my_worker:
    cron: '0 */2 * * * *' # Runs every 2 minutes
    class: MyWorker
    
